import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/bars/Navbar'
import Footer from '@/components/sections/Footer'
import Bottombar from '@/components/bars/Bottonbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Postafolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <body className={inter.className}>
      <Navbar />
      <main className='flex flex-row'>
        <section className='w-full'>
          <div >
            {children}
          </div>
        </section>
      </main>
      <div className='mt-60'>
        <Footer />
      </div>
      <Bottombar />
    </body>
  </html>
  )
}
